[prune]
  non-go = true
  unused-packages = true
  go-tests = true

[[constraint]]
  branch = "master"
  name = "github.com/jguer/go-alpm"

[[constraint]]
  branch = "master"
  name = "github.com/mikkeloscar/aur"

[[constraint]]
  branch = "master"
  name = "github.com/mikkeloscar/gopkgbuild"
