name: Build
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths-ignore:
      - "doc/**"
      - "README.md"
      - ".gitignore"
  pull_request:

jobs:
  build:
    name: Lint and test yay
    # This job runs on Linux
    runs-on: ubuntu-latest
    container: samip537/archlinux:devel
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Build and tests
        run: |
          pacman -Sy --noconfirm go
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.25.1
          ./bin/golangci-lint run ./...
          make test
