name: Test against pacman
on:
  pull_request:

jobs:
  build:
    name: Lint and test yay
    runs-on: ubuntu-latest
    container:
      image: jguer/yay-builder:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Lint
        env:
          GOFLAGS: -buildvcs=false
        run: /app/bin/golangci-lint run ./...
      - name: Run Build and Tests
        run: make test
      - name: Run Integration Tests
        continue-on-error: true
        run: |
          useradd -m yay &&
          chown -R yay:yay . &&
          cp -r ~/go/ /home/yay/go/ &&
          chown -R yay:yay /home/yay/go/ &&
          su yay -c "make test-integration"
